Add rPush and lPop to redis service
ElrondNetwork/erdnest pull request #94
Opened 2022-12-19 15:20 UTC by danielailie

2022-12-21 15:09 UTC, gabrielmatei requested changes

2022-12-21 15:09 UTC, gabrielmatei commented on packages/common/src/common/caching/redis-cache/redis-cache.service.ts
> +  async lpop<T>(key: string, items: any): Promise<T | null> {
use `T[]` type for items

2022-12-21 15:09 UTC, gabrielmatei commented on packages/common/src/common/caching/redis-cache/redis-cache.service.ts
> +  async rpush<T>(key: string, items: any): Promise<T | null> {
same here

2022-12-21 15:43 UTC, gabrielmatei approved these changes

2022-12-21 15:57 UTC, johnykes approved these changes

2022-12-21 16:13 UTC, gabrielmatei submitted a review, later dismissed

2022-12-21 16:15 UTC, johnykes approved these changes

2022-12-22 08:39 UTC, gabrielmatei approved these changes

2022-12-22 09:48 UTC, tanghel approved these changes

2022-12-22 09:48 UTC, merged