Add jwt or native guard
ElrondNetwork/erdnest pull request #96
Opened 2022-12-21 15:04 UTC by danielailie

2022-12-21 15:07 UTC, gabrielmatei requested changes

2022-12-21 15:07 UTC, gabrielmatei commented on packages/common/src/guards/jwt.or.native.auth.guard.ts
> +import { CachingService } from "src/common/caching/caching.service";
use relative paths for imports

2022-12-21 15:07 UTC, gabrielmatei commented on packages/common/src/guards/jwt.or.native.auth.guard.ts
> +export class JwtOrNativeAuthGuard implements CanActivate {
export file in `index.ts`

2022-12-21 15:14 UTC, danielailie commented on packages/common/src/guards/jwt.or.native.auth.guard.ts
> +import { CachingService } from "src/common/caching/caching.service";
done

2022-12-21 15:14 UTC, danielailie commented on packages/common/src/guards/jwt.or.native.auth.guard.ts
> +export class JwtOrNativeAuthGuard implements CanActivate {
done

2022-12-21 15:14 UTC, gabrielmatei approved these changes

2022-12-21 15:16 UTC, johnykes approved these changes

2022-12-22 08:39 UTC, gabrielmatei approved these changes

2022-12-22 09:45 UTC, tanghel approved these changes

2022-12-22 09:45 UTC, merged